name: Publish Zack! Website
on: [push, pull_request]
jobs:
  publish:
    name: CD - Push to server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2

      - name: Install PHP dependencies
        run: composer install --working-dir website --no-dev --prefer-dist --no-progress --no-suggest --optimize-autoloader

      - name: Rename index-prod.php
        run: rm website/web/index.php && mv website/web/index-prod.php website/web/index.php

      - name: Deploy to server via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          source: "website"
          target: ${{ secrets.SSH_TARGET }}
          rm: true
          strip_components: 1
